# Generated by Django 3.0.6 on 2020-05-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_auto_20200508_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.CharField(default='Добавим позже', max_length=128),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='skills',
            field=models.CharField(default='Скоро обновим', max_length=128),
        ),
    ]
